### ISSUE TITLE
Key repeat

### ISSUE THREAD

**Issue by rgbkrk** [jdfreder/poster#81]
OMG, this is so slick Jon. I just tried [your demo](http://jdfreder.github.io/poster/) out and noticed that holding down a keypress doesn't repeat that key.

**Comment by montanaflynn** [comment]
What system are you running? Worked for me using Mac OS X Yosemite with Chrome.

**Comment by rgbkrk** [comment]
Mavericks with Chrome

**Comment by jdfreder** [comment]
Thanks for @rgbkrk for reporting this.  I can verify that it's a problem in master.

**Comment by jdfreder** [comment]
I think this is caused by OSX's press&hold feature.  The clipboard management textbox, which is offscreen, is displaying the press&hold alternatives dialog (as seen below).  CodeMirror and Ace display their clipboard management textboxs behind the editor instead of offscreen.  The clipboard management textbox is then moved to the primary cursor's location as it changes so the alternatives dialog always shows in the right place.

![pressandholdfailure](https://cloud.githubusercontent.com/assets/3292874/6472476/b19d9bd4-c1a7-11e4-9a0a-34fdf79483a0.png)

Also, poster doesn't even handle the dialog correctly.  The character selected by the user should be entered into the textbox.

I think the solution for Poster is the same as Ace & CodeMirror, the textbox needs to exist where the cursor is and Poster needs to respect the key selection.  To be honest, I'd rather just disable press and hold altogether, but I'm not sure that's doable.

@rgbkrk you may want to try disabling the option in your OS settings - http://www.defaults-write.com/disable-press-and-hold-option-in-mac-os-x-10-7/#.VPYovFPF8Wc .

**Comment by rgbkrk** [comment]
It's not like I actually use this, I was just curious because I wanted to see how fast it was rendering and letting me type.

**Comment by jdfreder** [comment]
It look's like the keydown event bypasses the OSX accent menu and is repeated, but there's still the stick business of trying to hide the accent menu.  For now I'm going to mark this as won't fix, an OS setting will make it work, but maybe I'll try addressing it again in +2.0.
